Avoidance of duplicate code in regularisation
ourownstory/neural_prophet pull request #1110
Opened 2023-01-11 22:14 UTC by leoniewgnr

## :microscope: Background
As mentioned in issue #712, there is duplicate code regarding the event and holiday implementation.

## :crystal_ball: Key changes
This commit removes duplicate code in the regularisation of events and holidays (`def reg_func_events` in `utils.py`) by removing duplicate code and putting it into a helper function.

## :clipboard: Review Checklist
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, added docstrings and data types to function definitions.
- [ ] I have added pytests to check whether my feature / fix works.

2023-01-25 19:03 UTC, LeonieFreisinger requested changes

2023-01-25 19:03 UTC, LeonieFreisinger commented on neuralprophet/time_dataset.py
> +    def create_event_features(event, config):
The function name might be a little confusing since it is almost the same as `make_events_features()`

2023-01-30 11:34 UTC, leoniewgnr commented
@LeonieFreisinger, thanks for you feedback! I included it in the lates commits. But I don't know why `Linters / isort` and `Linters / black` keep failing. 

- `Linters / isort`: The order of inputs is exactly the same as in main
- `Linters / black`: It tells me that it would reformat` utils.py`, but I let black run before committing and there were no changes in `utils.py`. In addition, it suggests reformatting in lines of code where I did not change anything

2023-02-06 20:01 UTC, LeonieFreisinger approved these changes
Thanks for cleaning up that part of the code!! I have added only two more comments. The rest is good to go.

2023-02-06 20:01 UTC, LeonieFreisinger commented on neuralprophet/utils.py
> +    Helper function for reg_func_events to avoid code duplication
same here

2023-02-08 21:19 UTC, merged