Documentation for conditional seasonality
ourownstory/neural_prophet pull request #1116
Opened 2023-01-15 02:40 UTC by judussoari

## :crystal_ball: Key changes

Extends #1067 
Added docstring example, as well as a new tutorial notebook for conditional seasonality

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

2023-01-25 22:06 UTC, judussoari commented
@ourownstory when you or someone else review this, please have a look at the new helper function with the pre-implmented conditional seasonalities, and evaluate whether it makes sense

2023-01-25 22:06 UTC, judussoari commented
@ourownstory when you or someone else review this, please have a look at the new helper function with the pre-implmented conditional seasonalities, and evaluate whether it makes sense

2023-02-08 05:31 UTC, ourownstory requested changes
Great work!

RE:tutorial:

- mention helper functions
- explain what a condition is/must be
- plot_params: just plot Seasonalities

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/df_utils.py
> +def add_weekend_condition(df):
maybe rename to weekday - make weekdays 1

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/df_utils.py
> +def add_four_seasons_condition(df, soft_transition=0):
transition_period: steps to linearly interpolate between the two

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/df_utils.py
> +def add_four_seasons_condition(df, soft_transition=0):
note: Northern hemisphere

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/forecaster.py
> +            >>> df["summer_week"] = df["ds"].apply(lambda x: x.month in [6, 7, 8])
"summer_week", can drop week

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/forecaster.py
> +    def add_condition_to_df(self, df, condition="four_seasons", soft_transition=0):
I think we can use the df_utils directly!

2023-02-08 05:31 UTC, ourownstory commented on neuralprophet/df_utils.py
> +def add_four_seasons_condition(df, soft_transition=0):
quarter instead of four seasons?

2023-02-09 01:22 UTC, karl-richter approved these changes
Looks good!

2023-02-09 01:25 UTC, merged