[minor] Support data without datestamps
ourownstory/neural_prophet pull request #1188
Opened 2023-03-02 23:01 UTC by SimonWittner

## :microscope: Background

- Processing equidistant-data without datestamps
- Closes #18 

## :crystal_ball: Key changes

- Created a helper function to add equidistant datestamps 
- Function can be manually called and adjusted to the required dates and frequency 
- Function is automatically called if df consists only of column "y"

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

2023-03-08 21:10 UTC, karl-richter commented
Hi @SimonWittner, I know you are just getting started with this pr - but maybe have a look at [this](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md). This will make it easier to have meaningful commit messages, pr titles and so on :)

Also, the model/metrics pytest does currently not work from forks yet. You can it if that pytest fails for now.

2023-03-22 06:07 UTC, judussoari commented on neuralprophet/df_utils.py
> +            list of IDsgithubn
?

2023-04-13 06:04 UTC, ourownstory requested changes
Thank you @SimonWittner for your contribution!

While I was thinking of adding true support for data without datestamps, which would be entail large codebase changes, your approach is a rather simple alternative that may get the job done. I think this is a good addition, so I'd like to proceed to get your contribution merge-ready.
To do so, I suggest to still do the following:
- rename mentions of 'random' to 'dummy' or 'placeholder'
- use seconds as the frequency (to avoid issues with very long time-series)
- make sure to disable auto-seasonality when your code is triggered. (as the daily/weekly/yearly seasonalities will have no meaning)
- May there be a better location (less nested and less frequently called) than `prep_or_copy_df` for your code to be called?
- Add to the user warning that the frequency was set to seconds
- soft suggestion: have the function only return a series of datestamps, (no passing of df), and use a more efficient implementation of adding the column to the df than concat (outside the function).

Please let me know if you disagree with my suggestions or have further ideas

2023-04-26 21:12 UTC, leoniewgnr requested changes

2023-04-26 21:12 UTC, leoniewgnr commented on neuralprophet/df_utils.py
> +            list of IDsgithubn
sollte da nicht `IDs` stehen?

2023-04-26 22:52 UTC, leoniewgnr requested changes
Looks good so far but I think we should also support m.make_future_dataframe

2023-04-27 03:45 UTC, leoniewgnr approved these changes
LGTM

2023-04-27 17:47 UTC, ourownstory requested changes
Good changes!

I noticed that the model is passed to the datestamp creation function. 
Let us separate the disabling (editing of model config) from the timestamps creation.
So, for datestamp creation function, let us not pass the model, but only the precise args that are needed.

Further, the editing of model parameters (in a separate function), should not happen in `make_future_dataframe`. If seasonalities are enabled there and no datestamps present, it should create an error.

2023-04-27 17:47 UTC, ourownstory commented on neuralprophet/df_utils.py
> +def create_dummy_datestamps(
Looks good overall!

Let us separate the disabling (editing of model config) from the  timestamps creation.

So, for this function, let us not pass the model, but only the precise args that are needed.

2023-09-26 20:25 UTC, SimonWittner commented
Handling of data without datestamp fixed with https://github.com/ourownstory/neural_prophet/pull/1432

2023-09-26 20:25 UTC, closed without merging