Logistic growth
ourownstory/neural_prophet pull request #121
Opened 2020-11-10 23:44 UTC by Riley16

2020-12-16 22:41 UTC, ourownstory requested changes

2020-12-16 22:41 UTC, ourownstory commented on neuralprophet/time_net.py
> +    def init_logistic_growth(self, dataset, data_params):
let's run this init in a helper function

2020-12-16 22:41 UTC, ourownstory commented on neuralprophet/time_net.py
> +    def set_trend_cap(self, dataset):
can we run these checks before calling model?

2021-07-13 06:34 UTC, schlinge2000 commented
how is the status of this work? are you going to merge it?

2021-10-12 23:55 UTC, Riley16 commented
When is the publication date? I won't be able to get to it this weekend.
Maybe next weekend.

On Tue, Oct 12, 2021, 7:08 PM Oskar Triebe ***@***.***> wrote:

> how is the status of this work? are you going to merge it?
>
> @Riley16 <https://github.com/Riley16> Do you think you will still get to
> finish your great work?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ourownstory/neural_prophet/pull/121#issuecomment-941727910>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4SLASBP5WDMNRD2ZNIMS3UGS5YNANCNFSM4TRJJCIA>
> .
>

2022-03-31 09:42 UTC, closed without merging