Torch2
ourownstory/neural_prophet pull request #1373
Opened 2023-07-10 21:22 UTC by hxyue1

## :microscope: Background

- This is to upgrade neuralprophet to use pytorch 2.0 and address #1229

## :crystal_ball: Key changes

- Update the pyproject.toml file to use pytorch 2.0 and add optional CPU dependencies.

## :clipboard: Review Checklist
- [X] I have performed a self-review of my own code.
- [] I have commented my code, added docstrings and data types to function definitions.
- [] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

2023-07-31 11:46 UTC, noxan requested changes

2023-07-31 11:46 UTC, noxan commented on .github/workflows/ci.yml
> +        run: poetry update
```suggestion
```
The lockfile should not be automatically updated by our CI job, but rather locally - else we lose the benefits of locked dependencies from poetry.

Best update the lockfile locally - without updating any of the other dependencies with `poetry lock --no-update`

2023-07-31 11:46 UTC, noxan commented on .github/workflows/ci.yml
> +        run: poetry update
```suggestion
```

see above

2023-07-31 11:46 UTC, noxan commented on .github/workflows/linters.yml
> +        run: poetry update
```suggestion
```
see above

2023-07-31 11:46 UTC, noxan commented on pyproject.toml
> +torch = "^2.0.0"
```suggestion
torch = "^2.0.1"
```
there is torch 2.0.1 available already

2023-07-31 21:33 UTC, hxyue1 commented
Unfortunately this fails on windows with python 3.8 for some reason, but is fine in all other scenarios. The flake8 and pyright jobs are also failing but I haven't made changes to any python code so I'm not sure why that's the case.

2023-08-16 23:29 UTC, noxan commented
@hxyue1, thanks for the update and your work. To better understand the different problems you encountered, I drafted #1404.

I am not a big fan of forcing the `cpu` version of Pytorch - see my comment https://github.com/ourownstory/neural_prophet/issues/1229#issuecomment-1681393452 - let's come up with a plan there and then get one of the pull requests merged.

2023-09-11 18:52 UTC, leoniewgnr commented
@hxyue1 I will close this for now because #1404 fixes it, but feel free to open it again if you need it.

2023-09-11 18:52 UTC, closed without merging