[minor] add subdivisions to holidays
ourownstory/neural_prophet pull request #1584
Opened 2024-06-14 19:42 UTC by MaiBe-ctrl

## :microscope: Background

- closes #1574 

## :crystal_ball: Key changes

- Explain the main changes introduced by this pull request for the reviewer.

## :clipboard: Review Checklist
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, added docstrings and data types to function definitions.
- [x] I have added pytests to check whether my feature / fix works.

Please make sure to follow our best practices in the [Contributing guidelines](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md).

2024-06-14 23:37 UTC, MaiBe-ctrl commented
chnage the country parameter to accept a dict or str to list and omit the new added parameter!

2024-06-17 21:03 UTC, ourownstory requested changes
merge `get_country_holidays` into `get_holidays_from_country` and move to `hdays_utils`

2024-06-17 21:04 UTC, ourownstory commented on neuralprophet/forecaster.py
> +                name or list of names of the country or a dictionary where the key is the country name and the value is a list of subdivisions
remove list  (of subdivisions)

2024-06-20 05:30 UTC, ourownstory approved these changes
Looking good overall! I just suggest to move the `get_holidays_from_country` to `hday_utils.py`

2024-06-20 05:30 UTC, ourownstory commented on neuralprophet/configure.py
> +    def get_holidays_from_country(self, country: Union[str, Iterable[str], dict], df=None):
`self` does not appear to be accessed in this method. I think we can safely move it to `hdays_utils.py`.

2024-06-21 00:13 UTC, ourownstory commented
@MaiBe-ctrl Looks like you missed one utility function that was in `time_dataset.py`. I moved it to `hday_utils.py`. It was also not supporting subdivisions, so I added support for that, too. There is a lot of simplification potential to reduce the code in  `hday_utils.py`, but we can leave that for the refactoring post-JIT.

2024-06-21 00:15 UTC, ourownstory approved these changes
Feel free to merge once tests pass.

2024-06-21 00:31 UTC, merged