[refactor] TorchProphet
ourownstory/neural_prophet pull request #854
Opened 2022-10-18 19:23 UTC by karl-richter

- Added epochs + batch size to wrapper tests (speed up)
- Resolved warnings resulting from TorchProphet
- Updated plots in TorchProphet notebook
- Updated interval rounding in TorchProphet

2022-10-18 22:33 UTC, karl-richter commented
@ourownstory This pr contains all of the contents above as discussed. Can be merged asap from my side as I would consider it as bugfix.

2022-10-19 19:12 UTC, ourownstory requested changes

2022-10-19 19:12 UTC, ourownstory commented on neuralprophet/TorchProphet.py
>              remainder = 1 - interval_width
let's call remainder "alpha"

2022-10-20 19:10 UTC, ourownstory approved these changes

2022-10-20 19:11 UTC, merged