[bugfix] Fix index mismatch adding events when global df with multiple IDs is used
ourownstory/neural_prophet pull request #899
Opened 2022-10-25 00:13 UTC by judussoari

Fixes #879

2022-10-25 22:07 UTC, ourownstory requested changes
Good!
Let's also do an index reset in _make_future_dataframe for both events and future regressors.
That will also resolve #799

2022-10-25 22:07 UTC, ourownstory commented on neuralprophet/df_utils.py
> +            df.reset_index(drop=True, inplace=True)
never mind, lets keep this

2022-10-25 23:08 UTC, judussoari commented
> 

index reset is already performed in `_make_future_dataframe()` for both `events_df` and `regressors_df`. Ready to merge!

2022-10-26 19:18 UTC, ourownstory approved these changes
LGTM!

2022-10-26 19:18 UTC, merged