[feature] Covar net with shared weights
ourownstory/neural_prophet pull request #903
Opened 2022-10-25 18:33 UTC by karl-richter

**Status quo**
For each covariate (aka lagged regressor), a seperate net is trained.

**Change**
All lagged regressors share a network.

2022-11-06 17:21 UTC, alfonsogarciadecorral commented
Hi @karl-richter it looks good to me in terms of model architecture changes

![Screenshot 2022-11-06 at 16 22 31_903](https://user-images.githubusercontent.com/35847472/200185220-ef32161d-ddb1-4a68-b2ae-9c8c78d1db4e.png)
![Screenshot 2022-11-06 at 16 50 36_main](https://user-images.githubusercontent.com/35847472/200185221-da52b2d9-bf92-4f6c-b9c6-541cc2cb04a6.png)

2022-11-18 19:12 UTC, karl-richter commented
Update: this pr is currently failing under the migration to Lightning, since Lightning abstracts the migration of tensors between accelerators and the CPU, the information required to calculate model attributions using Captum seems lost. 

The following exception is raised in line 91 of utils_torch.py when calculating the attributions using:
`target_attribution = saliency.attribute(model_input, target=[(output_feature, quantile)], abs=False)`

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/karl/git/neural_prophet/venv/lib/python3.8/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/karl/git/neural_prophet/venv/lib/python3.8/site-packages/captum/attr/_core/saliency.py", line 130, in attribute
    gradients = self.gradient_func(
  File "/Users/karl/git/neural_prophet/venv/lib/python3.8/site-packages/captum/_utils/gradient.py", line 119, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(outputs), inputs)
  File "/Users/karl/git/neural_prophet/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

My suspicion is that Lightning removes the information required to use autograd from the model output, which would be nessecary to calculate gradients.

2022-12-01 11:23 UTC, alfonsogarciadecorral commented
Hey @karl-richter 

What do you mean with

"Inspect plot_components of lagged regressors (seems to be always proportional for the sum of all regressors)"

2022-12-01 22:41 UTC, karl-richter commented
> Hey @karl-richter
> 
> What do you mean with
> 
> "Inspect plot_components of lagged regressors (seems to be always proportional for the sum of all regressors)"

Hi @alfonsogarciadecorral, in the plot_components, we have to distribute the joint covariate forecast to each of the covariates (one seperate plot of the forecast of each covariate). With the current method of distributing the attributions, it seems like each variable gets attributed evenly at each point. I will post an example later.

2022-12-22 09:26 UTC, karl-richter commented on neuralprophet/forecaster.py
> +                            df_forecast = pd.concat([df_forecast, yhat_df], axis=1, ignore_index=False)
[for reviewer]: this cause pandas warnings with the previous implementation. Now fixed.

2022-12-22 09:27 UTC, karl-richter commented on neuralprophet/time_net.py
> +)
[for reviewer] importing utils directly caused an cyclic dependency error, thus we import all functions seperatly

2023-04-12 11:15 UTC, alfonsogarciadecorral requested changes
Hi @karl-richter @ourownstory 

Nice one, I think this is a nice improvement!

A few things from me:

- `num_hidden_layers` - Maybe we can rename this to `num_hidden_layers_lagged_regressors` or, if want to share with ar_net, `num_hidden_layers_lagged`.  For example, Im building a shared network for future_regressors and I should be able to use a different configuration.
- Out of curiosity, how come you use that function/formula to create `d_hidden` if it is not passed by user? 
- Would it make sense to pass the neural network architecture as an array? Something like `covar_net_layers_array` which would replace current `n_hidden` and `num_hidden_layers`

2023-04-16 11:02 UTC, alfonsogarciadecorral commented
Hey @karl-richter  @ourownstory  

The commit I did was about removing `num_hidden_layer` and  `d_hidden` and instead initialiting the `ar_net` and `covar_net` networks through then new variables: `ar_net_layers_array` and  `covar_net_layers_array`

Have a look, because it implies a few changes:
- We remove all which was related with `num_hidden_layer` and  `d_hidden` . So now the user either specifies the network or it assumes `num_hidden_layers=0`. There is no option to pass the `num_hidden_layers` and then getting the `d_hidden` through a heuristic method.
- config_model --> this will no longer contain `num_hidden_layer` and  `d_hidden` and it will have the `covar_net_layers_array`
- I removed the possibilty of passing the ‘local’ network on method `add_lagged_regressor` as it is a shared network now.

If you agree on the new changes there are two things missing that I will do as soon as you give thumbs up
**IMPORTANT -MISSING:**
- Change tutorials documentation to remove the `num_hidden_layer` and  `d_hidden`
- Add an warn message saying that `num_hidden_layer` and  `d_hidden` is not used anymore

2023-04-26 00:35 UTC, ourownstory approved these changes
Excellent work @karl-richter and @alfonsogarciadecorral !!

2023-04-26 00:36 UTC, ourownstory approved these changes

2023-04-26 01:38 UTC, merged