[feature] Add a main script to print neuralprophet version
ourownstory/neural_prophet pull request #974
Opened 2022-11-17 20:06 UTC by noxan

Allows users to run `python -m neuralprophet --version` and receive the version information of the package directly from their terminal. Could be extended in the future to a cli application of neuralprophet.

2022-11-23 23:51 UTC, ourownstory requested changes
Nice addition!
Let's just use the long flag "--version".
Let's remove "-v", which is often used for verbose

2022-11-24 02:31 UTC, noxan commented
@ourownstory Good point. Should we go with `-V` for version (capital letter) or fully remove the short version?

2022-11-24 02:32 UTC, noxan commented on neuralprophet/__main__.py
> +    parser.add_argument("-v", "--version", action="version", version="%(prog)s " + __version__)
Remove `-v` option

```suggestion
    parser.add_argument("--version", action="version", version="%(prog)s " + __version__)
```

2022-11-24 02:32 UTC, noxan commented on neuralprophet/__main__.py
> +    parser.add_argument("-v", "--version", action="version", version="%(prog)s " + __version__)
Use capital letter `-V` for version shorthand

```suggestion
    parser.add_argument("-V", "--version", action="version", version="%(prog)s " + __version__)
```

2022-12-02 05:21 UTC, karl-richter approved these changes

2022-12-02 05:24 UTC, merged